#!/usr/bin/env python3
"""Generates the #[repr(C)] structs the native engine needs from sherpa-onnx's own C header, so the layout
is never transcribed by hand: a field out of order would be memory corruption, not a compile error.

    curl -sL https://raw.githubusercontent.com/k2-fsa/sherpa-onnx/v<VERSION>/sherpa-onnx/c-api/c-api.h -o c-api.h
    python3 scripts/gen-sherpa-ffi.py c-api.h <VERSION> > src-tauri/engine/src/sherpa_ffi.rs

Only the structs reachable from the offline recognizer's and the offline TTS's configs are emitted; the
functions are looked up at run time (libloading) in `sherpa.rs`, against a library of exactly this version
(the catalog pins it).
"""
import re
import sys

ROOTS = ['SherpaOnnxOfflineRecognizerConfig', 'SherpaOnnxOfflineTtsConfig', 'SherpaOnnxGenerationConfig',
         'SherpaOnnxGeneratedAudio']
SCALARS = {
    'const char *': '*const c_char', 'char *': '*mut c_char', 'int32_t': 'i32', 'int64_t': 'i64', 'float': 'f32',
    'double': 'f64', 'const float *': '*const f32', 'float *': '*mut f32', 'const int32_t *': '*const i32',
    'const char **': '*const *const c_char', 'int': 'i32',
}


def structs(header):
    text = re.sub(r'/\*.*?\*/', '', header, flags=re.S)
    text = re.sub(r'//[^\n]*', '', text)
    found = {}
    for match in re.finditer(r'typedef struct (\w+) \{(.*?)\} (\w+);', text, re.S):
        name, body, alias = match.groups()
        assert name == alias, name
        fields = []
        for declaration in body.split(';'):
            declaration = ' '.join(declaration.split())
            if not declaration:
                continue
            field = re.match(r'(.*?)(\w+)$', declaration)
            ctype, fname = field.group(1).strip(), field.group(2)
            ctype = re.sub(r'\s*\*', ' *', ctype).replace('* *', '**').strip()
            fields.append((ctype, fname))
        found[name] = fields
    return found


def rust_type(ctype, known):
    if ctype in SCALARS:
        return SCALARS[ctype], None
    if ctype in known:
        return ctype, ctype
    raise SystemExit(f'unmapped C type: {ctype!r}')


def main():
    header_path, version = sys.argv[1], sys.argv[2]
    known = structs(open(header_path).read())
    order, seen = [], set()

    def visit(name):
        if name in seen:
            return
        seen.add(name)
        for ctype, _ in known[name]:
            _, nested = rust_type(ctype, known)
            if nested:
                visit(nested)
        order.append(name)

    for root in ROOTS:
        visit(root)
    out = [f'//! Generated by scripts/gen-sherpa-ffi.py from sherpa-onnx v{version} `sherpa-onnx/c-api/c-api.h`.',
           '//! Do not edit: regenerate for another version (and pin that version in the catalog).',
           '//! sherpa-onnx is Apache-2.0 (https://github.com/k2-fsa/sherpa-onnx).',
           '#![allow(non_camel_case_types, non_snake_case, dead_code)]', '',
           'use std::os::raw::c_char;', '',
           f'pub const HEADER_VERSION: &str = "{version}";', '']
    for name in order:
        out.append('#[repr(C)]')
        out.append('#[derive(Clone, Copy)]')
        out.append(f'pub struct {name} {{')
        for ctype, fname in known[name]:
            rtype, _ = rust_type(ctype, known)
            out.append(f'    pub {fname}: {rtype},')
        out.append('}')
        out.append('')
        # All-zero is a valid "unset" for every field (null pointers, zeros): what sherpa-onnx's own examples do
        # with memset before filling in what they use.
        out.append(f'impl Default for {name} {{')
        out.append('    fn default() -> Self {')
        out.append('        // SAFETY: plain C data; zero is null / 0 / 0.0 for every field.')
        out.append('        unsafe { std::mem::zeroed() }')
        out.append('    }')
        out.append('}')
        out.append('')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
